#pragma once

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 800
//60 fps
#define TARGET_MICROSECONDS_PER_FRAME		16667ULL

#define CELL_SIZE 20

#define GRID_X (SCREEN_WIDTH / CELL_SIZE)
#define GRID_Y (SCREEN_HEIGHT / CELL_SIZE)

